# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rfcontrol.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'rfcontrol.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0frfcontrol.proto\x12\trfcontrol\"?\n\tRFRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x11\n\tfrequency\x18\x02 \x01(\x01\x12\x0c\n\x04gain\x18\x03 \x01(\x01\".\n\nRFResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\"\n\rDeviceRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t\"q\n\x14\x44\x65viceStatusResponse\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x11\n\tfrequency\x18\x02 \x01(\x01\x12\x0c\n\x04gain\x18\x03 \x01(\x01\x12\x12\n\nref_locked\x18\x04 \x01(\x08\x12\x11\n\tlo_locked\x18\x05 \x01(\x08\"5\n\rRangeResponse\x12\x11\n\tmin_value\x18\x01 \x01(\x01\x12\x11\n\tmax_value\x18\x02 \x01(\x01\"%\n\x10PPStringResponse\x12\x11\n\tpp_string\x18\x01 \x01(\t2\xed\x02\n\x0cRFController\x12<\n\rsetRFSettings\x12\x14.rfcontrol.RFRequest\x1a\x15.rfcontrol.RFResponse\x12L\n\x0fgetDeviceStatus\x12\x18.rfcontrol.DeviceRequest\x1a\x1f.rfcontrol.DeviceStatusResponse\x12\x44\n\x0bgetPPString\x12\x18.rfcontrol.DeviceRequest\x1a\x1b.rfcontrol.PPStringResponse\x12\x42\n\x0cgetGainRange\x12\x18.rfcontrol.DeviceRequest\x1a\x18.rfcontrol.RangeResponse\x12G\n\x11getFrequencyRange\x12\x18.rfcontrol.DeviceRequest\x1a\x18.rfcontrol.RangeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rfcontrol_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RFREQUEST']._serialized_start=30
  _globals['_RFREQUEST']._serialized_end=93
  _globals['_RFRESPONSE']._serialized_start=95
  _globals['_RFRESPONSE']._serialized_end=141
  _globals['_DEVICEREQUEST']._serialized_start=143
  _globals['_DEVICEREQUEST']._serialized_end=177
  _globals['_DEVICESTATUSRESPONSE']._serialized_start=179
  _globals['_DEVICESTATUSRESPONSE']._serialized_end=292
  _globals['_RANGERESPONSE']._serialized_start=294
  _globals['_RANGERESPONSE']._serialized_end=347
  _globals['_PPSTRINGRESPONSE']._serialized_start=349
  _globals['_PPSTRINGRESPONSE']._serialized_end=386
  _globals['_RFCONTROLLER']._serialized_start=389
  _globals['_RFCONTROLLER']._serialized_end=754
# @@protoc_insertion_point(module_scope)
